# Generated by Django 5.2.1 on 2025-05-21 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0002_animal_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao', models.TextField(max_length=500)),
                ('genero', models.CharField(max_length=200)),
                ('idade', models.DecimalField(decimal_places=0, max_digits=3)),
                ('foi_adotado', models.BooleanField(default=False)),
                ('raca', models.CharField(max_length=200)),
                ('tamanho', models.CharField(max_length=200)),
                ('imagens', models.ImageField(upload_to='fotos/animais')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animal')),
            ],
        ),
    ]
