# Generated by Django 5.2 on 2025-07-03 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('aceito', models.BooleanField(default=False)),
                ('processado', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_adocao', to='pet.pet')),
                ('usuario_interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_feitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_pedido'],
            },
        ),
    ]
