# Generated by Django 5.2.1 on 2025-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
