# Generated by Django 5.2 on 2025-05-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_nome', models.CharField(max_length=80, unique=True)),
                ('animal_descricao', models.TextField(blank=True, max_length=255)),
                ('animal_imagem', models.ImageField(blank=True, upload_to='fotos/animais')),
            ],
        ),
    ]
